\documentclass[a4paper]{article}
\usepackage[margin=1.0in]{geometry}
\usepackage{longtable}
\usepackage{graphicx}
\usepackage{grffile}
<<echo=false>>=
options(width=60);
@
\SweaveOpts{eps=FALSE,pdf=TRUE}
\title{Metabolomic Data Analysis with MetaboAnalyst 5.0}
\author{ Name: guest18358687840321369509 }
\begin{document}
\parskip=.3cm
\maketitle
\section{Background}
 The Pathway Analysis module combines results from powerful pathway  enrichment analysis with pathway topology analysis to help researchers identify the most relevant pathways involved in the conditions under study. 

 There are many commercial pathway analysis software tools such as Pathway Studio, MetaCore, or Ingenuity Pathway Analysis (IPA), etc. Compared to these commercial tools, the pathway analysis module was specifically developed  for metabolomics studies. It uses high-quality KEGG metabolic pathways as the backend knowledgebase.  This module integrates many well-established (i.e. univariate analysis, over-representation analysis) methods, as well as novel algorithms and concepts (i.e. Global Test, GlobalAncova, network topology analysis) into pathway analysis. Another feature is a Google-Map style interactive visualization system to deliver  the analysis results in an intuitive manner.
\section{Data Input}
 The Pathway Analysis module accepts either a list of compound labels (common names, HMDB IDs or KEGG IDs) with one compound per row,  or a compound concentration table with samples in rows and compounds in columns. The second column must be  phenotype labels (binary, multi-group, or continuous). The table is uploaded as comma separated values (.csv). 

\section{Compound Name Matching}

The first step is to standardize the compound labels used in user uploaded data. This is a necessary step since
these compounds will be subsequently compared with compounds contained in the pathway library.
There are three outcomes from the step - exact match, approximate match (for common names only), and no match.
Users should click the textbf{View} button from the approximate matched results to manually select the correct one.
Compounds without match will be excluded from the subsequently pathway analysis.



\textbf{Table 1} shows the conversion results. Note: \textit{1} indicates exact match, \textit{2}
indicates approximate match, and \textit{0} indicates no match. A text file contain the result can be
found the downloaded file \textit{name\_map.csv}


<<echo=false, results=tex>>=
GetMapTable(mSet)
@
\clearpage


\section{Pathway Analysis}

In this step, users are asked to select a pathway library, as well as specify the algorithms for pathway
enrichment analysis and pathway topology analysis. 

\subsection{Pathway Library}

There are 15 pathway libraries currently supported, with a total of 1173 pathways :

\begin{itemize}
\item{Homo sapiens (human) [80]}
\item{Mus musculus (mouse) [82]}
\item{Rattus norvegicus (rat) [81]}
\item{Bos taurus (cow) [81]}
\item{Danio rerio (zebrafish) [81]}
\item{Drosophila melanogaster (fruit fly) [79]}
\item{Caenorhabditis elegans (nematode) [78]}
\item{Saccharomyces cerevisiae (yeast) [65]}
\item{Oryza sativa japonica (Japanese rice) [83]}
\item{Arabidopsis thaliana (thale cress) [87]}
\item{Escherichia coli K-12 MG1655 [87]}
\item{Bacillus subtilis [80]}
\item{Pseudomonas putida KT2440 [89]}
\item{Staphylococcus aureus N315 (MRSA/VSSA)[73]}
\item{Thermotoga maritima [57]}
\end{itemize}



Your selected pathway library code is \textbf{ osa }(KEGG organisms abbreviation).


\subsection{Over Representation Analysis}

Over-representation analysis tests if a particular group of compounds
is represented more than expected by chance within the user uploaded compound
list. In the context of pathway analysis, we are testing if compounds involved
in a particular pathway are enriched compared to random hits. MetPA offers two of the
most commonly used methods for over-representation analysis: 

\begin{itemize}
\item{Fishers'Exact test}
\item{Hypergeometric Test}
\end{itemize}
\textit{Please note, MetPA uses one-tailed Fisher's exact test which will give essentially
the same result as the result calculated by the hypergeometric test.}






\subsection{Pathway Topology Analysis}

The structure of biological pathways represent our knowledge about the complex relationships among molecules
within a cell or a living organism. However, most pathway analysis algorithms fail to take structural information
into consideration when estimating which pathways are significantly changed under conditions of study. 
It is well-known that changes in more important positions of a network will trigger a more severe
impact on the pathway than changes occurred in marginal or relatively isolated positions.



The pathway topology analysis uses two well-established node centrality measures to estimate node importance - \textbf{degree centrality}
and \textbf{betweenness centrality}. Degree centrality is defined as the number of links occurred upon a node.
For a directed graph there are two types of degree: in-degree for links come from other nodes, and out-degree
for links initiated from the current node. Metabolic networks are directed graph. Here we only consider the
out-degree for node importance measure. It is assumed that nodes upstream will have regulatory roles for
the downstream nodes, not vice versa. The betweenness centrality measures the number of shortest paths going
through the node. Since the metabolic network is directed, we use the relative betweenness centrality for a metabolite
as the importance measure. The degree centrality measure focuses more on local connectivities, while the betweenness
centrality measure focuses more on global network topology. For more detailed discussions on various graph-based
methods for analyzing biological networks, please refer to the article by Tero Aittokallio, T. et al.
\footnote{Tero Aittokallio and Benno Schwikowski. \textit{Graph-based methods for analyzing networks in cell biology},
Briefings in Bioinformatics 2006 7(3):243-255}



\textit{Please note, for comparison among different pathways, the node importance values calculated from centrality measures
are further normalized by the sum of the importance of the pathway. Therefore, the total/maximum importance of each pathway
is 1; the importance measure of each metabolite node is actually the percentage w.r.t the total pathway importance,
and the pathway impact value is the cumulative percentage from the matched metabolite nodes.}





\section{Pathway Analysis Result}

The results from pathway analysis are presented graphically as well as in a detailed table.



A Google-map style interactive visualization system was implemented to facilitate data exploration.
The graphical output contains three levels of view: \textbf{metabolome view}, \textbf{pathway view},
and \textbf{compound view}. Only the metabolome view is shown below.
Pathway views and compound views are generated dynamically based on your interactions with the
visualization system. They are available in your downloaded files. 

\begin{figure}[htp]
\begin{center}
\includegraphics[width=1.0\textwidth]{path_view_0_dpi72.png}
\caption{Summary of Pathway Analysis}
\end{center}
\label{path_view_0_dpi72.png}
\end{figure}
\clearpage


The table below shows the detailed results from the pathway analysis. Since
we are testing many pathways at the same time, the statistical p values from
enrichment analysis are further adjusted for multiple testings. In particular, 
the \textbf{Total} is the total number of compounds in the pathway;
the \textbf{Hits} is the actually matched number from the user uploaded data;
the \textbf{Raw p} is the original p value calculated from the enrichment analysis;
the \textbf{Holm p} is the p value adjusted by Holm-Bonferroni method;
the \textbf{FDR p} is the p value adjusted using False Discovery Rate;
the \textbf{Impact} is the pathway impact value calculated from pathway topology analysis.


<<echo=false, results=tex>>=
GetORATable(mSet)
@
\clearpage


\section{Appendix: R Command History}
<<echo=false, results=verbatim>>=
GetRCommandHistory(mSet);
@
\vspace{5 mm}
--------------------------------

 The report was generated on \Sexpr{date()} with \Sexpr{print(version$version.string)}, OS system: \Sexpr{Sys.info()['sysname']}, version: \Sexpr{gsub('#[0-9]+', '', Sys.info()['version'])} .
 \end{document}

